[package]
name = "minissh2-ring"
version = "0.0.1-dev"
publish = false
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "1"
minissh2 = { path = ".." }
ring = "0.16"
tokio = "1"
